style = "default"
always_for_in = false
always_use_return = true
annotate_untyped_fields_with_any = true
conditional_to_if = false
margin = 1000
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
trailing_comma = false
trailing_zero = false
whitespace_in_kwargs = false
whitespace_ops_in_indices = true
whitespace_typedefs = true